name:                fihles
version:             0.1.0.0
github:              "heiziff/fihles"
license:             BSD-3-Clause
author:              "Felix Zimmer"
maintainer:          "zimmer.felix01@gmail.com"
copyright:           "2024 Felix Zimmer"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/heiziff/fihles#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- http-types
- directory
- text
- blaze-html
- wai
- warp
- filepath
- utf8-string

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  fihles:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fihles

tests:
  fihles-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fihles
